[functions]
  external_node_modules = ["ejs","express", "mongodb", "serverless-http", "dotenv"]
  node_bundler = "esbuild"
  included_files = ["views/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200